// Autogenerated by Thrift Compiler (0.9.2)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package thrift

import (
	"bytes"
	"fmt"
	"git.apache.org/thrift.git/lib/go/thrift"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = bytes.Equal

type ThriftService interface {
	// Parameters:
	//  - Cmd
	//  - Seq
	//  - Body
	DoProcess(cmd string, seq string, body *ThriftCmdStruct) (r *ThriftResultStrcut, err error)
}

type ThriftServiceClient struct {
	Transport       thrift.TTransport
	ProtocolFactory thrift.TProtocolFactory
	InputProtocol   thrift.TProtocol
	OutputProtocol  thrift.TProtocol
	SeqId           int32
}

func NewThriftServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *ThriftServiceClient {
	return &ThriftServiceClient{Transport: t,
		ProtocolFactory: f,
		InputProtocol:   f.GetProtocol(t),
		OutputProtocol:  f.GetProtocol(t),
		SeqId:           0,
	}
}

func NewThriftServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *ThriftServiceClient {
	return &ThriftServiceClient{Transport: t,
		ProtocolFactory: nil,
		InputProtocol:   iprot,
		OutputProtocol:  oprot,
		SeqId:           0,
	}
}

// Parameters:
//  - Cmd
//  - Seq
//  - Body
func (p *ThriftServiceClient) DoProcess(cmd string, seq string, body *ThriftCmdStruct) (r *ThriftResultStrcut, err error) {
	if err = p.sendDoProcess(cmd, seq, body); err != nil {
		return
	}
	return p.recvDoProcess()
}

func (p *ThriftServiceClient) sendDoProcess(cmd string, seq string, body *ThriftCmdStruct) (err error) {
	oprot := p.OutputProtocol
	if oprot == nil {
		oprot = p.ProtocolFactory.GetProtocol(p.Transport)
		p.OutputProtocol = oprot
	}
	p.SeqId++
	if err = oprot.WriteMessageBegin("doProcess", thrift.CALL, p.SeqId); err != nil {
		return
	}
	args := DoProcessArgs{
		Cmd:  cmd,
		Seq:  seq,
		Body: body,
	}
	if err = args.Write(oprot); err != nil {
		return
	}
	if err = oprot.WriteMessageEnd(); err != nil {
		return
	}
	return oprot.Flush()
}

func (p *ThriftServiceClient) recvDoProcess() (value *ThriftResultStrcut, err error) {
	iprot := p.InputProtocol
	if iprot == nil {
		iprot = p.ProtocolFactory.GetProtocol(p.Transport)
		p.InputProtocol = iprot
	}
	_, mTypeId, seqId, err := iprot.ReadMessageBegin()
	if err != nil {
		return
	}
	if mTypeId == thrift.EXCEPTION {
		error0 := thrift.NewTApplicationException(thrift.UNKNOWN_APPLICATION_EXCEPTION, "Unknown Exception")
		var error1 error
		error1, err = error0.Read(iprot)
		if err != nil {
			return
		}
		if err = iprot.ReadMessageEnd(); err != nil {
			return
		}
		err = error1
		return
	}
	if p.SeqId != seqId {
		err = thrift.NewTApplicationException(thrift.BAD_SEQUENCE_ID, "doProcess failed: out of sequence response")
		return
	}
	result := DoProcessResult{}
	if err = result.Read(iprot); err != nil {
		return
	}
	if err = iprot.ReadMessageEnd(); err != nil {
		return
	}
	value = result.GetSuccess()
	return
}

type ThriftServiceProcessor struct {
	processorMap map[string]thrift.TProcessorFunction
	handler      ThriftService
}

func (p *ThriftServiceProcessor) AddToProcessorMap(key string, processor thrift.TProcessorFunction) {
	p.processorMap[key] = processor
}

func (p *ThriftServiceProcessor) GetProcessorFunction(key string) (processor thrift.TProcessorFunction, ok bool) {
	processor, ok = p.processorMap[key]
	return processor, ok
}

func (p *ThriftServiceProcessor) ProcessorMap() map[string]thrift.TProcessorFunction {
	return p.processorMap
}

func NewThriftServiceProcessor(handler ThriftService) *ThriftServiceProcessor {

	self2 := &ThriftServiceProcessor{handler: handler, processorMap: make(map[string]thrift.TProcessorFunction)}
	self2.processorMap["doProcess"] = &thriftServiceProcessorDoProcess{handler: handler}
	return self2
}

func (p *ThriftServiceProcessor) Process(iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	name, _, seqId, err := iprot.ReadMessageBegin()
	if err != nil {
		return false, err
	}
	if processor, ok := p.GetProcessorFunction(name); ok {
		return processor.Process(seqId, iprot, oprot)
	}
	iprot.Skip(thrift.STRUCT)
	iprot.ReadMessageEnd()
	x3 := thrift.NewTApplicationException(thrift.UNKNOWN_METHOD, "Unknown function "+name)
	oprot.WriteMessageBegin(name, thrift.EXCEPTION, seqId)
	x3.Write(oprot)
	oprot.WriteMessageEnd()
	oprot.Flush()
	return false, x3

}

type thriftServiceProcessorDoProcess struct {
	handler ThriftService
}

func (p *thriftServiceProcessorDoProcess) Process(seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	args := DoProcessArgs{}
	if err = args.Read(iprot); err != nil {
		iprot.ReadMessageEnd()
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err.Error())
		oprot.WriteMessageBegin("doProcess", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush()
		return false, err
	}

	iprot.ReadMessageEnd()
	result := DoProcessResult{}
	var retval *ThriftResultStrcut
	var err2 error
	if retval, err2 = p.handler.DoProcess(args.Cmd, args.Seq, args.Body); err2 != nil {
		x := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing doProcess: "+err2.Error())
		oprot.WriteMessageBegin("doProcess", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush()
		return true, err2
	} else {
		result.Success = retval
	}
	if err2 = oprot.WriteMessageBegin("doProcess", thrift.REPLY, seqId); err2 != nil {
		err = err2
	}
	if err2 = result.Write(oprot); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.WriteMessageEnd(); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.Flush(); err == nil && err2 != nil {
		err = err2
	}
	if err != nil {
		return
	}
	return true, err
}

// HELPER FUNCTIONS AND STRUCTURES

type DoProcessArgs struct {
	Cmd  string           `thrift:"cmd,1" json:"cmd"`
	Seq  string           `thrift:"seq,2" json:"seq"`
	Body *ThriftCmdStruct `thrift:"body,3" json:"body"`
}

func NewDoProcessArgs() *DoProcessArgs {
	return &DoProcessArgs{}
}

func (p *DoProcessArgs) GetCmd() string {
	return p.Cmd
}

func (p *DoProcessArgs) GetSeq() string {
	return p.Seq
}

var DoProcessArgs_Body_DEFAULT *ThriftCmdStruct

func (p *DoProcessArgs) GetBody() *ThriftCmdStruct {
	if !p.IsSetBody() {
		return DoProcessArgs_Body_DEFAULT
	}
	return p.Body
}
func (p *DoProcessArgs) IsSetBody() bool {
	return p.Body != nil
}

func (p *DoProcessArgs) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return fmt.Errorf("%T read error: %s", p, err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return fmt.Errorf("%T field %d read error: %s", p, fieldId, err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.ReadField1(iprot); err != nil {
				return err
			}
		case 2:
			if err := p.ReadField2(iprot); err != nil {
				return err
			}
		case 3:
			if err := p.ReadField3(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return fmt.Errorf("%T read struct end error: %s", p, err)
	}
	return nil
}

func (p *DoProcessArgs) ReadField1(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return fmt.Errorf("error reading field 1: %s", err)
	} else {
		p.Cmd = v
	}
	return nil
}

func (p *DoProcessArgs) ReadField2(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return fmt.Errorf("error reading field 2: %s", err)
	} else {
		p.Seq = v
	}
	return nil
}

func (p *DoProcessArgs) ReadField3(iprot thrift.TProtocol) error {
	p.Body = &ThriftCmdStruct{}
	if err := p.Body.Read(iprot); err != nil {
		return fmt.Errorf("%T error reading struct: %s", p.Body, err)
	}
	return nil
}

func (p *DoProcessArgs) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("doProcess_args"); err != nil {
		return fmt.Errorf("%T write struct begin error: %s", p, err)
	}
	if err := p.writeField1(oprot); err != nil {
		return err
	}
	if err := p.writeField2(oprot); err != nil {
		return err
	}
	if err := p.writeField3(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return fmt.Errorf("write field stop error: %s", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return fmt.Errorf("write struct stop error: %s", err)
	}
	return nil
}

func (p *DoProcessArgs) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("cmd", thrift.STRING, 1); err != nil {
		return fmt.Errorf("%T write field begin error 1:cmd: %s", p, err)
	}
	if err := oprot.WriteString(string(p.Cmd)); err != nil {
		return fmt.Errorf("%T.cmd (1) field write error: %s", p, err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return fmt.Errorf("%T write field end error 1:cmd: %s", p, err)
	}
	return err
}

func (p *DoProcessArgs) writeField2(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("seq", thrift.STRING, 2); err != nil {
		return fmt.Errorf("%T write field begin error 2:seq: %s", p, err)
	}
	if err := oprot.WriteString(string(p.Seq)); err != nil {
		return fmt.Errorf("%T.seq (2) field write error: %s", p, err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return fmt.Errorf("%T write field end error 2:seq: %s", p, err)
	}
	return err
}

func (p *DoProcessArgs) writeField3(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("body", thrift.STRUCT, 3); err != nil {
		return fmt.Errorf("%T write field begin error 3:body: %s", p, err)
	}
	if err := p.Body.Write(oprot); err != nil {
		return fmt.Errorf("%T error writing struct: %s", p.Body, err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return fmt.Errorf("%T write field end error 3:body: %s", p, err)
	}
	return err
}

func (p *DoProcessArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DoProcessArgs(%+v)", *p)
}

type DoProcessResult struct {
	Success *ThriftResultStrcut `thrift:"success,0" json:"success"`
}

func NewDoProcessResult() *DoProcessResult {
	return &DoProcessResult{}
}

var DoProcessResult_Success_DEFAULT *ThriftResultStrcut

func (p *DoProcessResult) GetSuccess() *ThriftResultStrcut {
	if !p.IsSetSuccess() {
		return DoProcessResult_Success_DEFAULT
	}
	return p.Success
}
func (p *DoProcessResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DoProcessResult) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return fmt.Errorf("%T read error: %s", p, err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return fmt.Errorf("%T field %d read error: %s", p, fieldId, err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 0:
			if err := p.ReadField0(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return fmt.Errorf("%T read struct end error: %s", p, err)
	}
	return nil
}

func (p *DoProcessResult) ReadField0(iprot thrift.TProtocol) error {
	p.Success = &ThriftResultStrcut{}
	if err := p.Success.Read(iprot); err != nil {
		return fmt.Errorf("%T error reading struct: %s", p.Success, err)
	}
	return nil
}

func (p *DoProcessResult) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("doProcess_result"); err != nil {
		return fmt.Errorf("%T write struct begin error: %s", p, err)
	}
	if err := p.writeField0(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return fmt.Errorf("write field stop error: %s", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return fmt.Errorf("write struct stop error: %s", err)
	}
	return nil
}

func (p *DoProcessResult) writeField0(oprot thrift.TProtocol) (err error) {
	if p.IsSetSuccess() {
		if err := oprot.WriteFieldBegin("success", thrift.STRUCT, 0); err != nil {
			return fmt.Errorf("%T write field begin error 0:success: %s", p, err)
		}
		if err := p.Success.Write(oprot); err != nil {
			return fmt.Errorf("%T error writing struct: %s", p.Success, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 0:success: %s", p, err)
		}
	}
	return err
}

func (p *DoProcessResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DoProcessResult(%+v)", *p)
}
