# This is a TOML document. Boom.

[Log]
Level = "debug"

[Server]
Host = "192.168.10.25"
Port = 10087

[Configure]
Param = "192.168.10.25:18888,192.168.10.31:18888"

[AllocStrategy]
OrderClearThreshold = 5
OrderMinFreeSpace = 104857600
OrderConsumeCount = 3


