# This is a TOML document. Boom.

NeedleMaxSize  = 10485760

[Log]
Level = "debug"

[Block]
BufferSize      = 4194304
SyncWrite       = 1
Syncfilerange   = true

[Index]
BufferSize = 4096
SyncWrite   = 1
Syncfilerange = true

[Server]
Id = 1
Desc = "test[25]"
Host = "192.168.10.25"
Port = 10086

[Store]
VolumeIndex      = "volume_data/volume.idx"
FreeVolumeIndex  = "volume_data/free_volume.idx"

[Dir]
Path = ["volume_data"]
Capacity = [512]

[Configure]
Param = "192.168.10.25:18888,192.168.10.31:18888"

[Replication]
Path = "binlog"

