NeedleMaxSize  = 10485760

[Log]
Level = "debug"

[Block]
BufferSize      = 4194304
SyncWrite       = 1
Syncfilerange   = true

[Index]
BufferSize = 4096
SyncWrite   = 1
Syncfilerange = true

[Server]
Id = 1
Desc = "test[25]"
Host = "192.168.10.25"
Port = 10086

[Store]
VolumeIndex      = "/home/yimin/xqdfs/data/volume.idx"
FreeVolumeIndex  = "/home/yimin/xqdfs/data/free_volume.idx"

[Dir]
Path = ["/home/yimin/xqdfs/data"]
Capacity = [4096]

[Configure]
Param = "192.168.10.25:20010"

[Replication]
Path = "binlog"

